# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'ViewLayoutTestDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'LayoutExtension' ,:git => 'https://github.com/FelixYin66/LayoutExtension.git'

  # Pods for ViewLayoutTestDemo

end
